### PR TITLE
Added support for interfaces 

### PR DESCRIPTION
**Pull request by mohataher**
This version has one added feature:
- Interfaces can be used to represent Edges and Vertices
- Test cases were added to cover the newly added features.

Since multiple inheritance isn't supported in Java, using interfaces to implement some data models is needed. Therefore, I have extended the library to support using interfaces instead of abstract classes.

Please review the pull request and let me know if you need any changes.

### CODE REVIEW

**Comment by bayofmany** [comment]
Maven install is failing with java.lang.StringIndexOutOfBoundsException. Can you please fix it?
Please do not commit any jar files.

**Comment by mohataher** [comment]
How about now?

**Comment by bayofmany** [comment]
Not really. I fixed the substring issue in the master branch.
But your changes breaks to majority of the tests. Can you please review your code and verify using mvn install?

**Comment by mohataher** [comment]
This is getting weird because it's passing on my IDEA IDE at the moment. I will give it a try using mvn commands.

**Comment by mohataher** [comment]
ِAlright. All test cases pass now using mvn clean install.

**Comment by bayofmany** [comment]
Thanks for your contribution!

**Comment by mohataher** [comment]
Great. When should I expect the next release?

**Comment by bayofmany** [comment]
The interface feature is not sufficiently mature yet. I'm adding additional tests to deal with more corner cases. I can release just afterwards.

**Comment by bayofmany** [comment]
Tests are ok now. 0.2.1 released

**Comment by mohataher** [comment]
Excellent news. Thanks a lot.

**Pull request merged**
